@REM Align TheRock build with default.json ROCm stack (hipSdk + MIOpen).

@REM Excludes ORT/EP/ModelBench/MIGraphX/rocMLIR (not in TheRock).

@REM BinSkim / compliance: CFG (/guard:cf) + static MSVC CRT (/MT) where supported.

@REM After changing flags: re-run this script, then expunge/rebuild affected targets.

@REM Example: ninja -C build MIOpen+expunge amd-comgr+expunge hip-clr+expunge && ninja -C build



cmake -B build -GNinja . ^

	-DBUILD_TESTING=OFF -DTHEROCK_BUILD_TESTING=OFF ^

	-DTHEROCK_AMDGPU_TARGETS="gfx1100;gfx1101;gfx1102;gfx1103;gfx1150;gfx1151;gfx1152;gfx1153;gfx1200;gfx1201" ^

	-DTHEROCK_TEST_AMDGPU_TARGETS="gfx1100;gfx1101;gfx1102;gfx1103;gfx1150;gfx1151;gfx1152;gfx1153;gfx1200;gfx1201" ^

	-DTHEROCK_ENABLE_OCL_RUNTIME=OFF ^

	-DTHEROCK_ENABLE_COMM_LIBS=OFF ^

	-DTHEROCK_ENABLE_DC_TOOLS=OFF ^

	-DTHEROCK_ENABLE_DEBUG_TOOLS=OFF ^

	-DTHEROCK_ENABLE_STORAGE_LIBS=OFF ^

	-DTHEROCK_ENABLE_MEDIA_LIBS=OFF ^

	-DTHEROCK_ENABLE_EMULATION=OFF ^

	-DTHEROCK_ENABLE_ROCPROFSYS=OFF ^

	-DTHEROCK_ENABLE_HIPIFY=OFF ^

	-DTHEROCK_ENABLE_CORE_HIPINFO=OFF ^

	-DTHEROCK_ENABLE_CORE_HIPTESTS=OFF ^

	-DTHEROCK_ENABLE_MIOPEN_PLUGIN=OFF ^

	-DTHEROCK_ENABLE_HIPDNN=OFF ^

	-DTHEROCK_ENABLE_HIPDNN_INTEGRATION_TESTS=OFF ^

	-DTHEROCK_ENABLE_MIOPENPROVIDER=OFF ^

	-DTHEROCK_ENABLE_HIPBLASLTPROVIDER=OFF ^

	-DTHEROCK_ENABLE_HIPDNN_SAMPLES=OFF ^

	-DTHEROCK_ENABLE_HIPKERNELPROVIDER=OFF ^

	-DTHEROCK_ENABLE_ROCWMMA=OFF ^

	-DTHEROCK_ENABLE_PRIM=OFF ^

	-DTHEROCK_ENABLE_LIBHIPCXX=OFF ^

	-DTHEROCK_ENABLE_ROCALUTION=OFF ^

	-DTHEROCK_ENABLE_FFT=OFF ^

	-DTHEROCK_ENABLE_SPARSE=OFF ^

	-DTHEROCK_ENABLE_SOLVER=OFF ^

	-DTHEROCK_ENABLE_FFTW3=OFF ^

	-Damd-llvm_CMAKE_ARGS="-DLLVM_PARALLEL_LINK_JOBS=2;-DLLVM_USE_BINSKIM_COMPLIANT_COMPILE_FLAGS=ON;-DLLVM_USE_MSVC_STATIC_RUNTIME=ON;-DROCM_DEVICE_LIBS_USE_BINSKIM_COMPLIANT_COMPILE_FLAGS=ON;-DROCM_DEVICE_LIBS_USE_MSVC_STATIC_RUNTIME=ON;-DZLIB_USE_STATIC_LIBS=ON" ^

	-Damd-comgr_CMAKE_ARGS="-DCOMGR_DLL_NAME=amd_comgr0714.dll;-DCOMGR_DISABLE_SPIRV=OFF;-DCOMGR_EMBED_LIBCXX_HEADERS=ON;-DCOMGR_USE_INCBIN=OFF;-DCOMGR_USE_BINSKIM_COMPLIANT_COMPILE_FLAGS=ON;-DCOMGR_USE_MSVC_STATIC_RUNTIME=ON;-DZLIB_USE_STATIC_LIBS=ON" ^

	-Dhip-clr_CMAKE_ARGS="-D__HIP_USE_BINSKIM_COMPLIANT_COMPILE_FLAGS=ON;-DZLIB_USE_STATIC_LIBS=ON" ^

	-Drocm-kpack_CMAKE_ARGS="-DBUILD_SHARED_LIBS=OFF" ^

	-DrocRAND_CMAKE_ARGS="-DROCRAND_USE_BINSKIM_COMPLIANT_COMPILE_FLAGS=ON;-DROCRAND_USE_MSVC_STATIC_RUNTIME=ON" ^

	-DhipBLASLt_CMAKE_ARGS="-DCMAKE_POLICY_VERSION_MINIMUM=3.10;-DZLIB_USE_STATIC_LIBS=ON;-DHIPBLASLT_BUILD_TESTING=OFF;-DHIPBLASLT_ENABLE_CLIENT=OFF;-DHIPBLASLT_ENABLE_AMD_SMI=OFF;-DHIPBLASLT_ENABLE_FETCH=ON;-DTENSILELITE_BUILD_TESTING=OFF;-DHIPBLASLT_USE_BINSKIM_COMPLIANT_COMPILE_FLAGS=ON;-DHIPBLASLT_USE_MSVC_STATIC_RUNTIME=ON" ^

	-DrocBLAS_CMAKE_ARGS="-DROCBLAS_USE_BINSKIM_COMPLIANT_COMPILE_FLAGS=ON;-DROCBLAS_USE_MSVC_STATIC_RUNTIME=OFF" ^

	-DhipBLAS_CMAKE_ARGS="-DHIPBLAS_USE_BINSKIM_COMPLIANT_COMPILE_FLAGS=ON;-DHIPBLAS_USE_MSVC_STATIC_RUNTIME=ON" ^

	-Dcomposable_kernel_CMAKE_ARGS="-DCMAKE_POLICY_VERSION_MINIMUM=3.10;-DBUILD_CK_EXAMPLES=OFF;-DBUILD_CK_TUTORIALS=OFF;-DBUILD_DEV=OFF;-DCK_USE_BINSKIM_COMPLIANT_COMPILE_FLAGS=ON;-DCK_USE_MSVC_STATIC_RUNTIME=ON;-DENABLE_CLANG_CPP_CHECKS=OFF" ^

	-DMIOpen_CMAKE_ARGS="-DCMAKE_COMPILE_WARNING_AS_ERROR=ON;-DMIOPEN_BACKEND=HIP;-DMIOPEN_USE_SQLITE_PERFDB=ON;-DMIOPEN_USE_BINSKIM_COMPLIANT_COMPILE_FLAGS=ON;-DMIOPEN_USE_MSVC_STATIC_RUNTIME=ON"

